<?php
/**
 * Created by PhpStorm.
 * User: huaji001
 * Date: 2019/3/14
 * Time: 3:54 PM
 */

namespace frontend\controllers;


use common\common;
use yii\base\Controller;
use Yii;

class WeixinController extends Controller
{
    private $AppID;
    private $AppSecret;
    const ACCESS_TOKEN = 'https://api.weixin.qq.com/cgi-bin/token';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $weixin_params = Yii::$app->params['weixin'];
        $this->AppID = $weixin_params['AppID'];
        $this->AppSecret = $weixin_params['AppSecret'];
    }


    public function actionAccess_token()
    {
        $url = 'https://api.weixin.qq.com/cgi-bin/token';

        $params = [
            'grant_type' => 'client_credential',
            'appid' => $this->AppID,
            'secret' => $this->AppSecret
        ];

        return common::get($url,$params);
    }

    public function actionTest(){
        $url = "https://apiface.store.runnerbar.com/yundong/smsVerificationCode/getCode.json";
        $post= [
            'tel' => '15397986660',
            'type' => 8,
            'sign' => '761bd1b682b96fed052b3059c48e0f80',
            'patchca' => 'dew5',
            'uuid' => ''
        ];
        $data = common::curl_request($url,$post);
        var_dump($data);

    }
}